//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Business.WS_WMS_ATO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeATORequest", Namespace="urn:ATOWs")]
    [System.SerializableAttribute()]
    public partial class TypeATORequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SiteCodeField;
        
        private string PrincipalCodeField;
        
        private string ProdCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SiteCode {
            get {
                return this.SiteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteCodeField, value) != true)) {
                    this.SiteCodeField = value;
                    this.RaisePropertyChanged("SiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string PrincipalCode {
            get {
                return this.PrincipalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrincipalCodeField, value) != true)) {
                    this.PrincipalCodeField = value;
                    this.RaisePropertyChanged("PrincipalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ProdCode {
            get {
                return this.ProdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodeField, value) != true)) {
                    this.ProdCodeField = value;
                    this.RaisePropertyChanged("ProdCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeATOResponse", Namespace="urn:ATOWs")]
    [System.SerializableAttribute()]
    public partial class TypeATOResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        private string ReasonTextField;
        
        private int AvailableQtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ReasonText {
            get {
                return this.ReasonTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonTextField, value) != true)) {
                    this.ReasonTextField = value;
                    this.RaisePropertyChanged("ReasonText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AvailableQty {
            get {
                return this.AvailableQtyField;
            }
            set {
                if ((this.AvailableQtyField.Equals(value) != true)) {
                    this.AvailableQtyField = value;
                    this.RaisePropertyChanged("AvailableQty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ATOWs", ConfigurationName="WS_WMS_ATO.ATOWsPort")]
    public interface ATOWsPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="ATORequest", ReplyAction="*")]
        WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse ATORequest(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ATORequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse> ATORequestAsync(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ATORequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ATORequest", Namespace="urn:ATOWs", Order=0)]
        public WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequestBody Body;
        
        public ATORequestRequest() {
        }
        
        public ATORequestRequest(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:ATOWs")]
    public partial class ATORequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMSCustomerPortal.Business.WS_WMS_ATO.TypeATORequest ATO;
        
        public ATORequestRequestBody() {
        }
        
        public ATORequestRequestBody(WMSCustomerPortal.Business.WS_WMS_ATO.TypeATORequest ATO) {
            this.ATO = ATO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ATORequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ATOResponse", Namespace="urn:ATOWs", Order=0)]
        public WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponseBody Body;
        
        public ATORequestResponse() {
        }
        
        public ATORequestResponse(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:ATOWs")]
    public partial class ATORequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WMSCustomerPortal.Business.WS_WMS_ATO.TypeATOResponse ATO;
        
        public ATORequestResponseBody() {
        }
        
        public ATORequestResponseBody(WMSCustomerPortal.Business.WS_WMS_ATO.TypeATOResponse ATO) {
            this.ATO = ATO;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ATOWsPortChannel : WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATOWsPortClient : System.ServiceModel.ClientBase<WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort>, WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort {
        
        public ATOWsPortClient() {
        }
        
        public ATOWsPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATOWsPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATOWsPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATOWsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort.ATORequest(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest request) {
            return base.Channel.ATORequest(request);
        }
        
        public WMSCustomerPortal.Business.WS_WMS_ATO.TypeATOResponse ATORequest(WMSCustomerPortal.Business.WS_WMS_ATO.TypeATORequest ATO) {
            WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest inValue = new WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest();
            inValue.Body = new WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequestBody();
            inValue.Body.ATO = ATO;
            WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse retVal = ((WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort)(this)).ATORequest(inValue);
            return retVal.Body.ATO;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse> WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort.ATORequestAsync(WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest request) {
            return base.Channel.ATORequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestResponse> ATORequestAsync(WMSCustomerPortal.Business.WS_WMS_ATO.TypeATORequest ATO) {
            WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest inValue = new WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequest();
            inValue.Body = new WMSCustomerPortal.Business.WS_WMS_ATO.ATORequestRequestBody();
            inValue.Body.ATO = ATO;
            return ((WMSCustomerPortal.Business.WS_WMS_ATO.ATOWsPort)(this)).ATORequestAsync(inValue);
        }
    }
}
