//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_CONSIGN
    {
        public int rec_no { get; set; }
        public string SiteCode { get; set; }
        public string PrincipalCode { get; set; }
        public string ConsignState { get; set; }
        public string ConsignReceiptType { get; set; }
        public string ProdCode { get; set; }
        public string FullMoveRef { get; set; }
        public Nullable<int> ConsignQty { get; set; }
        public Nullable<int> Qty { get; set; }
        public string OrderLineNumber { get; set; }
        public string BookInType { get; set; }
        public string MoveRef { get; set; }
        public string PORef { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<int> WriteOffQty { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> PackagingWeight { get; set; }
        public string ArrReqd { get; set; }
        public string ArrSent { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<int> ConsignDisc { get; set; }
        public string ConsignType { get; set; }
        public string BatchFileName { get; set; }
        public string BatchState { get; set; }
    }
}
