//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_CUSTOMER
    {
        public int rec_no { get; set; }
        public string CustAccNo { get; set; }
        public string CustInvName { get; set; }
        public string CustInvAdd0 { get; set; }
        public string CustInvAdd1 { get; set; }
        public string CustInvAdd2 { get; set; }
        public string CustInvAdd3 { get; set; }
        public string CustInvAdd4 { get; set; }
        public string CustInvAdd5 { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string VATNumber { get; set; }
        public string BundleOrders { get; set; }
        public string PrintPrice { get; set; }
        public string PrintSerials { get; set; }
        public Nullable<int> DefaultPriority { get; set; }
    }
}
