//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_ORDER
    {
        public int rec_no { get; set; }
        public string SiteCode { get; set; }
        public string PrincipalCode { get; set; }
        public string OrderId { get; set; }
        public string OrderState { get; set; }
        public string Customer { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> StateChange { get; set; }
        public string CompanyName { get; set; }
        public string HeaderComment { get; set; }
        public string CustOrderNum { get; set; }
        public string SalesPerson { get; set; }
        public string SalesCategory { get; set; }
        public string Processor { get; set; }
        public string BundleOrder { get; set; }
        public string CName { get; set; }
        public string CAddr0 { get; set; }
        public string CAddr1 { get; set; }
        public string CAddr2 { get; set; }
        public string CAddr3 { get; set; }
        public string CAddr4 { get; set; }
        public string CAddr5 { get; set; }
        public string InvoiceTo { get; set; }
        public string WMSPostCode { get; set; }
        public Nullable<int> ExpectedParcels { get; set; }
        public Nullable<int> ActualParcelCount { get; set; }
        public string InvoicePrinted { get; set; }
        public string OCOSent { get; set; }
        public string MasterOrder { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryLabelAttached { get; set; }
        public string OrdProcessingType { get; set; }
        public string OrderStarted { get; set; }
        public Nullable<int> CartonCount { get; set; }
        public Nullable<int> CartonsToDispatch { get; set; }
        public Nullable<System.DateTime> CartonTime { get; set; }
    }
}
