//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_RDT
    {
        public int rec_no { get; set; }
        public string RdtId { get; set; }
        public string RdtIpAddress { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Comment { get; set; }
        public string MoverType { get; set; }
        public string Location { get; set; }
        public string WarehouseId { get; set; }
    }
}
