//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_REPLEN
    {
        public int rec_no { get; set; }
        public string ReplenState { get; set; }
        public string PickFace { get; set; }
        public string HighBay { get; set; }
        public string MoveReason { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> RdtNum { get; set; }
    }
}
