//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_SERIAL
    {
        public int rec_no { get; set; }
        public Nullable<int> TmId { get; set; }
        public string ProdCode { get; set; }
        public string SerialNumber { get; set; }
        public string MoveRef { get; set; }
        public Nullable<int> UnitWeight { get; set; }
        public Nullable<int> UnitPkgWeight { get; set; }
        public string Dispatched { get; set; }
        public string FirstPack { get; set; }
    }
}
