//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSCustomerPortal.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_TM
    {
        public int rec_no { get; set; }
        public string PrincipalCode { get; set; }
        public Nullable<int> TmId { get; set; }
        public string Location { get; set; }
        public string FinalDestination { get; set; }
        public string TmType { get; set; }
        public string TmState { get; set; }
        public string MoveReason { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> TmWeight { get; set; }
        public string SealNo { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string MoverType { get; set; }
        public Nullable<System.DateTime> PriorityDate { get; set; }
        public string Virgin { get; set; }
        public string TrueVirgin { get; set; }
        public Nullable<int> RecircCount { get; set; }
        public string WeightChecked { get; set; }
        public Nullable<int> MeasuredWeight { get; set; }
    }
}
